[FEAT] [송금] [송금 비밀번호 등록] [송금 완료 페이지] 구현
woorifisa-projects-3rd/WeKids-FE pull request #111
Opened 2024-11-30 09:32 UTC by AnChanUng

# 📄 Work Description

- 송금 뷰
- 송금 비밀번호 등록 뷰
- 송금 완료 뷰 구현

# ⚙️ ISSUE

- closed #108 

# 📷 Screenshot

- 동영상, 사진, 로그 등등
- ex) 큐알 성공 이미지, 스웨거, 포스트맨 등

- 송금 뷰 
![image](https://github.com/user-attachments/assets/d0ad427e-a919-46e0-bd7c-4fa5f6d8db91)

- 송금 비밀번호 등록 뷰 
![image](https://github.com/user-attachments/assets/fcff6010-5fd6-47f6-aca8-e82840ea1ce5)

- 송금 완료 뷰 구현
![image](https://github.com/user-attachments/assets/090ffd60-fae2-4351-a5fb-361f07848199)

# 💬 To Reviewers

리뷰어들에게 하고 싶은 말

- 메모 입력 추가
- 공유버튼 누르면 이동 못하게 수정
- 비밀번호 1번 누르면 이동하게 수정

2024-11-30 10:05 UTC, jabin1221 approved these changes
good

2024-11-30 10:51 UTC, cbj0010 reviewed
굿굿 코드가 아조 많이 나아졌네용

2024-11-30 10:51 UTC, cbj0010 commented on src/ui/components/signup/PasswordTop.jsx
> +            {title} <br /> 등록해 주세요.
아직 디자인 반영 안되어 있긴한데 '송금 비밀번호를 입력해주세요'가 맞을거 같아요!

2024-11-30 10:51 UTC, cbj0010 commented on src/ui/components/transfer/TransferComplete.jsx
> +      memo: "",
Memo 도 쓸거면 저번에 자빈님이 만들어 놓으신 memo 부분처럼 입력될 수 있게 Mem입력창도 ui에 넣어야 될거 같아요!

2024-11-30 10:51 UTC, cbj0010 commented on src/app/mission/transfer/password/page.jsx
> +          />
얘는 송금 할때는 값 재검증 하도록 두번 받는게 아니라 한번만 입력하는거죠?

2024-11-30 10:51 UTC, cbj0010 commented on src/ui/components/signup/PasswordBottom.jsx
> +
sleect 일때는 비밀번호 등록하는 창이고
transferdone은 송금할때 쓰는거 맞나요?

2024-12-01 10:18 UTC, cbj0010 requested changes
부모와 아이가 보이는 미션이 다르기 때문에 /mission이렇게 만드는게 아니라 app/parent/mission
이렇게 만드는게 맞을거 같아요.
그리고 ui/componets/mission 이렇게 파서 그 속에 컴포넌트를 넣는게 맞을거 같습니다.

그리고 최 상단 page 부분에는 <Header><ParentMissionHome></></> 뭐 이런식으로 컴포넌트로 넣는게 맞을거 같아요
최 상단에는 user client는 써주지 마시고요

그리고 link랑 route 언제써야 되나 좀 찾아봤는데 저의 결론은
Next.js 13 이상에서는 App Router를 사용할 때 'next/navigation'의 useRouter를 사용하도록 권장합니다. 하지만 이는 router.push 사용을 권장한다는 의미가 아니라, 필요한 상황에 따라 적절한 방식을 선택하라는 의미입니다:

1. 일반적인 네비게이션: Link 컴포넌트 사용
2. 프로그래밍 방식 라우팅 필요 시: useRouter 사용

따라서 기본적으로는 Link 컴포넌트를 사용하고, 특별한 라우팅 로직이 필요한 경우에만 router.push를 사용하는 것이 권장됩니다.

이거였습니다.

**내 리뷰에 대한 반박 환영**

2024-12-01 10:18 UTC, cbj0010 commented on src/app/(transfer)/transfer/done/page.jsx
>  "use client";
저희 오늘부터 page.jsx에는 use client사용 안하기로 합시다.. 서버 연결할때 너무 힘들대요

2024-12-01 10:18 UTC, cbj0010 commented on src/app/(transfer)/transfer/done/page.jsx
>    }
이것 지금 어디서 불러다가 쓰는거지?̊̈-?̊̈ 
이것도 route.push로 onclick이나 이런 이벤트 없으니까 Link로 바꿔주세요..
다른 곳에서 쓰는곳 있으면 use client 빼고 잘 돌아가나 확인해주시고••• 안돌아가면 고쳐서 올려주심 감사하겟습니다

2024-12-01 10:18 UTC, cbj0010 commented on src/app/mission/transfer/done/page.jsx
이것도 .page에서는 use client 사용하지 말아주세요잉 컴포넌트로 따로 빼서 하던 글케하자
zustand 꼭 써야 되는 상황 아니면 Props로 넘겨주고..
이 뷰가 어디 뷰인지 모르겠어서 모라 못하겠네

근데 지금 코드상으로 봤을 때는 useclient 안써도 되는걸로 보이긴 함

2024-12-01 10:18 UTC, cbj0010 commented on src/app/mission/transfer/page.jsx
이것도 client

2024-12-03 00:40 UTC, cbj0010 reviewed
컨플릭트 해결해서 다시 올려주세요

2024-12-03 07:43 UTC, cbj0010 reviewed
리뷰 확인해주시고 따봉 단거는 
Yes라는 답변을 한거라고 이해하면 될까요?

2024-12-03 07:43 UTC, cbj0010 commented on src/app/mission/transfer/done/page.jsx
> +};
const page = () => {
  return (
    <div>page</div>
  )
}

export default page

요거 요런식으로 쓰는게 함수형으로 더 적합하게 쓰는거래요 
rafce로 만들면 알아서 잘 생김

2024-12-03 07:43 UTC, cbj0010 commented on src/ui/components/atoms/Sharebutton.jsx
>      >
이거 버튼클릭 리스너 달지 말고 그냥 toast로 아직 준비중인 기능입니다! 이런거 띄우는게 나을거에요

2024-12-03 07:43 UTC, cbj0010 commented on src/ui/components/transfer/TransferComplete.jsx
> +              <p className="text-R-14 text-neutral-300 pt-2 px-4 py-2 bg-[#F5F5F5] rounded-[100px] inline-block">
색 하드코딩 바꿔주세요 round도 몬가요

2024-12-03 07:43 UTC, cbj0010 commented on src/ui/components/transfer/TransferComplete.jsx
> +        <div className="px-5 pb-8">
요거 꼭 div로 또 묶어야 되나요?

2024-12-04 02:47 UTC, cbj0010 approved these changes

2024-12-04 03:10 UTC, merged